import streamlit as st
import pandas as pd
from frontend.services.alert_service import load_alerts, resolve_alert, get_alerts_summary
from frontend.services.pricing_service import get_available_products

def show_page():
    st.title("🚨 Operational Risk & Alert Center")
    st.markdown("Monitor and manage supply, inventory, stockout, and price change warning alerts generated by the pricing engine.")
    st.markdown("---")

    summary = get_alerts_summary()
    df_alerts = load_alerts()

    # Alert Count Indicators
    col_open, col_high, col_resolved = st.columns(3)
    with col_open:
        # Red warning border for active risks
        border = "#e74a3b" if summary["open_count"] > 0 else "#1cc88a"
        st.markdown(
            f"""
            <div style="padding: 1rem; border-left: 5px solid {border}; border-radius: 6px; background-color: #ffffff; box-shadow: 0 0.15rem 1.75rem 0 rgba(58, 59, 120, 0.1);">
                <div style="font-size: 0.8rem; font-weight: bold; color: #858796; text-transform: uppercase;">Open Risks</div>
                <div style="font-size: 1.8rem; font-weight: 700; color: #2e303d; margin-top: 0.25rem;">{summary["open_count"]}</div>
            </div>
            """, 
            unsafe_allow_html=True
        )

    with col_high:
        border_high = "#e74a3b" if summary["high_severity_count"] > 0 else "#858796"
        st.markdown(
            f"""
            <div style="padding: 1rem; border-left: 5px solid {border_high}; border-radius: 6px; background-color: #ffffff; box-shadow: 0 0.15rem 1.75rem 0 rgba(58, 59, 120, 0.1);">
                <div style="font-size: 0.8rem; font-weight: bold; color: #858796; text-transform: uppercase;">High Severity Risks</div>
                <div style="font-size: 1.8rem; font-weight: 700; color: #2e303d; margin-top: 0.25rem;">{summary["high_severity_count"]}</div>
            </div>
            """, 
            unsafe_allow_html=True
        )

    with col_resolved:
        st.markdown(
            f"""
            <div style="padding: 1rem; border-left: 5px solid #1cc88a; border-radius: 6px; background-color: #ffffff; box-shadow: 0 0.15rem 1.75rem 0 rgba(58, 59, 120, 0.1);">
                <div style="font-size: 0.8rem; font-weight: bold; color: #858796; text-transform: uppercase;">Resolved Issues</div>
                <div style="font-size: 1.8rem; font-weight: 700; color: #2e303d; margin-top: 0.25rem;">{summary["resolved_count"]}</div>
            </div>
            """, 
            unsafe_allow_html=True
        )

    st.markdown("---")

    if df_alerts.empty:
        st.success("🎉 **All clear! No alerts have been logged in the system.**")
        return

    # Filter controls
    st.subheader("🔍 Filter Alert Log")
    col_sev, col_type, col_status = st.columns(3)
    
    with col_sev:
        sevs = ["All", "HIGH", "WARNING"]
        sel_sev = st.selectbox("Severity Level", sevs)
    with col_type:
        types = ["All", "LOW_STOCK", "STOCKOUT_RISK", "SUPPLY_RISK", "PRICE_CHANGE"]
        sel_type = st.selectbox("Alert Type", types)
    with col_status:
        statuses = ["All", "OPEN", "RESOLVED"]
        sel_status = st.selectbox("Resolution Status", statuses, index=1) # Default to open

    # Filter application
    df_filtered = df_alerts.copy()
    if sel_sev != "All":
        df_filtered = df_filtered[df_filtered["severity"] == sel_sev]
    if sel_type != "All":
        df_filtered = df_filtered[df_filtered["alert_type"] == sel_type]
    if sel_status != "All":
        df_filtered = df_filtered[df_filtered["status"] == sel_status]

    # Render filtered alerts list
    st.subheader("📋 Active Alert Registry")
    if df_filtered.empty:
        st.info("No alerts matched the selected filter configuration.")
    else:
        df_display = df_filtered.sort_values("timestamp", ascending=False).copy()
        df_display["timestamp"] = df_display["timestamp"].dt.strftime("%Y-%m-%d %H:%M:%S")

        # Custom cell formatting wrapper
        def highlight_alert(row):
            styles = [""] * len(row)
            status_idx = row.index.get_loc("status")
            sev_idx = row.index.get_loc("severity")
            
            if row["status"] == "OPEN":
                if row["severity"] == "HIGH":
                    styles[status_idx] = "background-color: #f8d7da; color: #721c24; font-weight: bold;"
                    styles[sev_idx] = "background-color: #f8d7da; color: #721c24; font-weight: bold;"
                else:
                    styles[status_idx] = "background-color: #fff3cd; color: #856404; font-weight: bold;"
                    styles[sev_idx] = "background-color: #fff3cd; color: #856404; font-weight: bold;"
            else:
                styles[status_idx] = "background-color: #d4edda; color: #155724;"
            return styles

        style_obj = df_display.style.apply(highlight_alert, axis=1)
        st.dataframe(style_obj, use_container_width=True, hide_index=True)

    # Resolution Form
    open_alerts_only = df_alerts[df_alerts["status"] == "OPEN"]
    if not open_alerts_only.empty:
        st.markdown("---")
        st.subheader("🛠️ Action Resolution Panel")
        st.markdown("Audit and mark identified system anomalies as resolved after mitigating the issue.")

        with st.form("resolve_alert_form"):
            options_list = []
            for _, row in open_alerts_only.iterrows():
                pid = row["product_id"]
                atype = row["alert_type"]
                msg = row["message"]
                options_list.append({
                    "sku": pid,
                    "type": atype,
                    "label": f"[{atype}] SKU: {pid} — {msg[:50]}..."
                })

            selected_opt = st.selectbox(
                "Select Open Alert to Resolve",
                options_list,
                format_func=lambda x: x["label"]
            )

            submit_resolve = st.form_submit_button("Mark as Resolved")
            if submit_resolve and selected_opt:
                success = resolve_alert(
                    product_id=selected_opt["sku"],
                    alert_type=selected_opt["type"]
                )
                if success:
                    st.success(f"Successfully marked {selected_opt['type']} alert for {selected_opt['sku']} as RESOLVED.")
                    st.rerun()
                else:
                    st.error("Failed to update alert state.")
